RulePath = "/etc/nginx/ngx_lua_waf/wafconf/"
attacklog = "on"
logdir = "/var/log/nginx/waf/"
UrlDeny="on"
Redirect="on"
CookieMatch="on"
postMatch="off" 
whiteModule="on"
ipWhitelist={"127.0.0.1"}
ipBlocklist={}
CCDeny="on"
CCrate="200/60"
html=[[<h1>Forbidden</h1><p>This page is blocked by USTC LUG Web Application Firewall.</p><p>If this is a legitimate page and you are seeing this message, please contact lug (AT) ustc.edu.cn.</p>]]
