RulePath = "/etc/nginx/ngx_lua_waf/wafconf/"
attacklog = "on"
logdir = "/var/log/nginx/waf/"
UrlDeny="on"
Redirect="on"
CookieMatch="on"
postMatch="on" 
whiteModule="on" 
ipWhitelist={"127.0.0.1"}
ipBlocklist={}
CCDeny="on"
CCrate="200/60"
html=[[This page is blocked by USTC LUG Web Application Firewall. If this is a legitimate page and you are seeing this message, please contact lug (AT) ustc.edu.cn.]]
